Ci/migration gha pr prerelease
newrelic/nri-couchbase pull request #45
Opened 2020-10-15 13:24 UTC by jportasa

2020-10-28 10:02 UTC, brushknight commented on build/package/windows/nri-386-installer/Product.wxs
> -            <Component Id="CMP_V1_CUSTOM_PLUGINS_BIN" Guid="e4509a7a-409e-4a38-8705-37de9cf0d72d" KeyPath="yes">
Is it fine to change this GUID?

2020-11-13 19:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/nri-couchbase?pullRequest=45) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/nri-couchbase?pullRequest=45) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: brushknight<br/>:x: Joan Porta<br/><hr/>**Joan Porta** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/nri-couchbase?pullRequest=45) it.</sub>

2021-01-18 10:14 UTC, paologallinaharbur commented on build/package/windows/nri-386-installer/Product.wxs
> -            <Component Id="CMP_V1_CUSTOM_PLUGINS_BIN" Guid="e4509a7a-409e-4a38-8705-37de9cf0d72d" KeyPath="yes">
Discussed offline, safe to change GUID

2021-01-18 10:41 UTC, roobre requested changes

2021-01-18 10:41 UTC, roobre commented on .github/workflows/push_pr.yml
> +        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```suggestion
        SNYK_TOKEN: ${{ secrets.COREINT_SNYK_TOKEN }}
```

2021-01-18 10:41 UTC, roobre commented on .github/workflows/prerelease.yml
> +        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```suggestion
        SNYK_TOKEN: ${{ secrets.COREINT_SNYK_TOKEN }}
```

2021-01-18 10:41 UTC, roobre commented on build/.goreleaser.yml
> +      "couchbase-definition.yml": "/var/db/newrelic-infra/newrelic-integrations/couchbase-definition.yml"
```suggestion
```

2021-01-18 15:15 UTC, roobre approved these changes
Nothing wrong seen here

2021-01-18 15:17 UTC, merged